sudo: false
language: python
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libatlas-base-dev
python:
  - "3.6"
  - "3.7"
install: pip install pythran
script: python run.py -tpython -tpythran

